# Generated by Django 6.0.2 on 2026-03-15 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("github_url", models.URLField()),
                ("language", models.CharField(default="unknown", max_length=50)),
                ("pep8_score", models.FloatField(null=True)),
                ("architecture_score", models.FloatField(null=True)),
                ("best_practices_score", models.FloatField(null=True)),
                ("files_analyzed", models.IntegerField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("status", models.CharField(default="pending", max_length=20)),
            ],
        ),
    ]
